theme: jekyll-theme-canyan
title: Liyu Cao(曹力予)
page-navigation: true
navbar:
  left:
    - file: index.md
      text: Home
  right:
    - icon: github
      href: https://github.com/leevvyy/leevvyy.github.io/
      aria-label: GitHub
